"""Configuration module."""

from ro_tax_agents.config.settings import Settings
from ro_tax_agents.config.prompts import (
    ENTRY_AGENT_SYSTEM_PROMPT,
    PFA_AGENT_SYSTEM_PROMPT,
    PROPERTY_SALE_AGENT_SYSTEM_PROMPT,
    RENTAL_INCOME_AGENT_SYSTEM_PROMPT,
    CERTIFICATE_AGENT_SYSTEM_PROMPT,
    EFACTURA_AGENT_SYSTEM_PROMPT,
    RAO_AGENT_SYSTEM_PROMPT,
)

__all__ = [
    "Settings",
    "ENTRY_AGENT_SYSTEM_PROMPT",
    "PFA_AGENT_SYSTEM_PROMPT",
    "PROPERTY_SALE_AGENT_SYSTEM_PROMPT",
    "RENTAL_INCOME_AGENT_SYSTEM_PROMPT",
    "CERTIFICATE_AGENT_SYSTEM_PROMPT",
    "EFACTURA_AGENT_SYSTEM_PROMPT",
    "RAO_AGENT_SYSTEM_PROMPT",
]
